# Generated by Django 5.0.9 on 2026-09-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_customizable',
            field=models.BooleanField(default=False, help_text='Opens the build-your-own ingredient builder instead of the simple option sheet'),
        ),
    ]
